<a href="https://colab.research.google.com/github/abhinao007/Code-tensorflow/blob/main/numpy_and_pandas_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np 
import pandas as pd

In [ ]:
mylist = [1,2,3,4,5,6,7,8]

In [ ]:
nested_list = [[1,2], [2,3], [4,5]]

In [ ]:
(np.array(mylist))


[1 2 3 4 5 6 7 8]
[[1 2]
 [2 3]
 [4 5]]


In [ ]:
(np.array(nested_list))

array([[1, 2],
       [2, 3],
       [4, 5]])

In [ ]:
np.arange(1,101, 4) # integer numbers aare created  # excluding the last number

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65,
       69, 73, 77, 81, 85, 89, 93, 97])

In [ ]:
np.zeros(3) # floating point numbers 

array([0., 0., 0.])

In [ ]:
np.zeros((2,4), dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
np.ones((4,4), dtype = int) 

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
np.linspace(2,4, 3) # evenly spaced numbers 

array([2., 3., 4.])

In [ ]:
np.eye(5) # identity matrix 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# random arrays 

In [ ]:
np.random.rand(2). # from a uniform distribution

array([0.83378763, 0.4700399 ])

In [ ]:
np.random.rand(2,3) # from a normal distribution 

array([[0.13421473, 0.103259  , 0.79598091],
       [0.87818258, 0.01990932, 0.04088569]])

In [ ]:
np.random.randn(5,5)

array([[-0.02684653, -1.91945532, -0.60510508, -2.19289626, -2.12320885],
       [ 0.85102198,  0.55188264, -0.35554171, -0.77051453,  0.03501253],
       [ 1.03053385,  0.59742421,  0.1046383 , -0.36002923,  0.48557416],
       [-1.15518926,  2.18839192, -1.05344316, -0.02419263,  0.98779444],
       [ 1.0303364 , -1.97057207, -2.10441605,  0.30382084,  0.564693  ]])

In [ ]:
np.random.randint(1,100,10)  # integer values 

array([21, 32, 37, 40, 44,  8, 40, 88, 71,  2])

In [3]:
ranarr = np.random.randint(1,100,(10,10))

In [7]:
np.random.seed(42) # fixed the random values 
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [6]:
print(ranarr.max())
print(ranarr.argmax())

print(ranarr.min())
print(ranarr.argmin())

98
51
1
70


# Next chapter

In [22]:
arr =np.arange(1,10)

In [23]:
arr[5]

6

In [24]:
arr[:19]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
# broadcasting

In [26]:
arr = np.arange(1,11)

In [27]:
arr[1:3]= 100

In [28]:
arr

array([  1, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [29]:
slice_of_arr = arr[1:7]
slice_of_arr

array([100, 100,   4,   5,   6,   7])

In [30]:
slice_of_arr[:] =100. # the assignment will affect the original arr array as the slice_of_array is pointing to original array --> thus broadcasting 

In [31]:
slice_of_arr

array([100, 100, 100, 100, 100, 100])

In [32]:
# this broadcasting is not present with list in python

In [33]:
array_2d = np.random.rand(3,3)
array_2d

array([[7.21998772e-01, 9.38552709e-01, 7.78765841e-04],
       [9.92211559e-01, 6.17481510e-01, 6.11653160e-01],
       [7.06630522e-03, 2.30624250e-02, 5.24774660e-01]])

In [34]:
array_2d.shape

(3, 3)

In [35]:
array_2d[:2,2:3]

array([[0.00077877],
       [0.61165316]])

In [36]:
arr = np.arange(1,11)

In [37]:
bol_arr = arr >4

In [38]:
arr[bol_arr]

array([ 5,  6,  7,  8,  9, 10])

# chapter 2

In [39]:
arr = np.arange(0,10)

In [40]:
arr +5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [41]:
arr_1 = arr  

In [42]:
arr_1 = arr_1 +1

In [43]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
arr_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
arr+arr_1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [46]:
arr/arr_1

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ,
       0.83333333, 0.85714286, 0.875     , 0.88888889, 0.9       ])

In [47]:
arr_1/arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 2.        , 1.5       , 1.33333333, 1.25      ,
       1.2       , 1.16666667, 1.14285714, 1.125     , 1.11111111])

In [48]:
arr_1*arr

array([ 0,  2,  6, 12, 20, 30, 42, 56, 72, 90])

In [49]:
np.sum(arr)

45

In [50]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [51]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [52]:
np.log(arr)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [53]:
np.var(arr)

8.25

In [54]:
np.std(arr)

2.8722813232690143

In [55]:
ar2d = np.random.rand(5,5)

In [56]:
ar2d.sum()

11.450422323993985

In [57]:
ar2d.sum(axis=0)

array([2.69396768, 1.72878807, 2.37450984, 2.27382206, 2.37933467])

# pandas 


In [3]:
# series

label = ['a', 'b','c']

mylist = [10,20,30]

d = {'a':10, 'b':20, 'c':30}



In [15]:
import pandas as pd

pd.Series(mylist ,label)
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [5]:
SalesQ1 = pd.Series(data= [100,200,300,250,500], index= ['Inida', 'USA', 'Brazil', 'South Africa', 'China'])

In [6]:
SalesQ1['China']
SalesQ1[4]


500

In [7]:
SalesQ2 = pd.Series(data= [100,200,300,250,500], index= ['Inida', 'USA', 'Brazil', 'South Africa', 'Russia'])

In [8]:
SalesQ1+SalesQ2

Brazil          600.0
China             NaN
Inida           200.0
Russia            NaN
South Africa    500.0
USA             400.0
dtype: float64

In [9]:
Column = ['A','B','C','D','E']
Index = ['W','X','Y','Z']


In [13]:
from numpy.random import randint
import numpy as np

In [14]:
np.random.seed(42)
data = randint(-100,100, (5,4))

In [16]:
df = pd.DataFrame(data, Column , Index)

In [17]:
df

W   X   Y   Z
A   2  79  -8 -86
B   6 -29  88 -80
C   2  21 -26 -13
D  16  -1   3  51
E  30  49 -48 -99

# dataframe is collection of series 

In [21]:
(df[['W', 'Z']]) 

W   Z
A   2 -86
B   6 -80
C   2 -13
D  16  51
E  30 -99

In [58]:
df['new'] = df['X'] + df['Y']

In [59]:
df

W   X   Y   Z  new
A   2  79  -8 -86   71
B   6 -29  88 -80   59
C   2  21 -26 -13   -5
D  16  -1   3  51    2
E  30  49 -48 -99    1

In [63]:
#reassign for permanent change
df = df.drop('new', axis = 1)

In [64]:
df.loc['A']

W     2
X    79
Y    -8
Z   -86
Name: A, dtype: int64